function [layers,options] = create_network(feature_dim,hidden_unit)
    layers = [
      sequenceInputLayer(feature_dim)
      
      lstmLayer(hidden_unit)
      reluLayer
      
      fullyConnectedLayer(1)
      regressionLayer
    ];

    options = trainingOptions('adam', ...
    'MiniBatchSize',100, ...
    'MaxEpochs',100, ...
    'InitialLearnRate',1e-5, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropFactor',0.5, ...
    'LearnRateDropPeriod', 50, ...
    'Plots','training-progress');
end

